include::sections/deconstruct_documentation.adoc[]

When?

* Knowledge needed for a long period of time -> Documented
* Knowledge needed by a large number of people -> Documented
* Knowledge valuable or critical -> Documented
* Default -> Don't


Generic Knowledge


* Programming languages
* Developer tools
* Software practices
*** DDD
*** patterns
*** CI
*** Git tuto
*** ...
* Mature sector of the business industries
** Pricing in finance
** Supply Chain Optimization in e-commerce
** -> Industry standard books

Good news! The Generic Knowledge is already documented in the industry literature.

* Training
* Conferences
* Books
* Blog posts
* Standard Vocabulary
* ...

-> Learn Generic Knowledge

Focus on specific knowledge

* Knowledge your organization has and is not (yet) shared with other peers in the same industry.
* more expensive to learn
* takes practice, making mistakes to earn
* Deserves more attention
* Only you can take care about it



As a professional, you should know enough of the generic, industry standard knowledge, in order to be able to focus on growing the knowledge that's specific to you particular ambitions.

include::sections/kinds_of_knowledge_transfer.adoc[]

include::sections/plain_text_documentation.adoc[]



=== Différentes caractéristiques

* Stable

TODO : tableau

* Statique, immuable, standard
* Dynamique, change souvent

== Stable

Evergreen document Ce qui est stable = ce qui est toujours vrai

* Standards
* Most of parts of common industry

tout ce qui bouge ailleurs

* marketing
* noms de sociétés
* les dates
* les gens

== What is unstable?

Les comportements métiers

BDD

Documentation exécutable

== !

Redondance

Quelle est la source de vérité?

Cucumber / Specflow -> réconciliation entre scénarios et code

=== How to deal with Stable/Unstable?

Stable:: Learn & refer to it
Unstable:: Automate it as much as possible when it is useful

=== En bref

* NoDocumentation
* Stable Documentation
* Refactor-Friendly Documentation
* Automated Documentation
* Runtime Documentation
* Beyond Documentation

[.notes]
--
J'utilise ici volontairement des termes en anglais issus du livre "Living Documentation" de Cyrille Martraire car faisant selon moi référence en la matière, ils faciliteront vos recherches et la propagation cohérente des ces concepts.
--


