== Living Documentation!

=== Core Principles of Living Documentation

=== Reliable

=== Low-Effort

=== Collaborative

=== Insightful

== Qualities of living documentation

[.notes]
--
* Ces qualités
--

=== Single sourced


[.notes]
--
* Single sourced = DRY de la doc
** On veut garantir qu'il y a une source unique pour une connaissance. Les représentations de cette connaissance devraient découler de cette source.
--


=== Reliable

[.notes]
--
* Reliable = fiable
** Crainte de l'obsolescence
** Source du problème est souvent que la documentation est externalisée par rapport à la source de connaissances
*** Ex. un fichier word % au code source
* \___ as code
* proche du code
* versionné dans le repo du code
* privilégier interne à externe (avec mécanisme de réconciliation)
--

[.columns]
=== Refactor Friendly

[.column]
--
* Put together things that change together (including documentation)
* Use code or language features to enable refactoring tooling
--

[.column]
--
++++
<iframe src='https://gfycat.com/ifr/PlushFeistyCondor' frameborder='0' scrolling='no' allowfullscreen width='250' height='450'></iframe>
++++
--

[.refs]
--
https://gfycat.com/ifr/PlushFeistyCondor
--

//=== Refactor-friendly
//
//* Correspondance nom entité -> Nom table
//* Solution pour réduire la friction entre le modèle de base de données et l'entité dans le code : annotation de correspondance
//
//[.notes]
//--
//* Refactor-friendly
//*** Ex. ORM : Changement de nom d'entité => changement de nom de table?
//**** Migration de nom de table
//**** Mécanisme de réconciliation : un correspondance entre le nom de la table et l'entité (annotation @Table Jpa)
//*** Ex. un commentaire dans le code % un nom de méthode
//--

=== Before refactoring

[source, java]
----
@Entity // Table name -> ADDRESS
public class Address{
    public Long id;
    public String line1;
    //...
}
----

[.notes]
--
* Par défaut dans hibernate, le nom de la classe d'une entité est converti en nom de table dans la base de données.
--

=== After refactoring

[source, java]
----
@Entity // Table name -> DELIVERY_ADDRESS
public class DeliveryAddress{
    public Long id;
    public String line1;
    //...
}
----

[.notes]
--
* L'ORM et ses conventions nous freinent
--

=== Explicit mapping before refacto

[source,java]
----
@Entity
@Table(name="ADDRESS") // Table name -> ADDRESS
public class Address{
    public Long id;
    public String line1;
    //...
}
----

=== Explicit mapping after refacto

[source,java]
----
@Entity
@Table(name="ADDRESS") // Table name -> ADDRESS
public class DeliveryAddress{
    public Long id;
    public String line1;
    //...
}
----

[.notes]
--
* L'annotation @Table fait office de mécanisme de réconciliation (entre notre code et la base de données)
* Le mécanisme de réconciliation a permis de découpler le nom de l'entité dans le code à son nom dans le modèle de données
* On s'autorise à penser qu'il n'y a pas forcément un miroir structurel entre le modèle de base de donnée, des classes de domaine, et les API exposées
--
