= Tu ne le sais pas encore mais tu l'as déjà documenté!
:author: Marc Bouvier
:copyright: CC-BY-4.0

Proposition de talk pour l'Agile tour 2021 à Strasbourg.
Au sujet de la documentation vivante.

- https://www.meetup.com/fr-FR/MugStrasbourg/events/281350303/
- https://u.baldir.fr/at-2021-ld
- https://u.baldir.fr/at-2021-stras

link:docs/index.adoc[Index des slides]

== Generation des slides

=== Asciidoctor-revealjs

Install : https://docs.asciidoctor.org/reveal.js-converter/latest/setup/node-js-setup/

[source,bash]
----
cd docs
npm install
# Test Cli is available
npx asciidoctor-revealjs --version
----

Génération

[source,bash]
----
./generatedoc.sh
----

[source,pwsh]
----
./generatedoc.ps1
----

== License

Creative Commons Attribution 4.0 International
See link:LICENSE[]

You are free to:

* *Share* — copy and redistribute the material in any medium or format
* *Adapt* — remix, transform, and build upon the material
for any purpose, even commercially.

The licensor cannot revoke these freedoms as long as you follow the license terms.

Under the following terms:

* *Attribution* — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
* *No additional restrictions* — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.