---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: side_projects_in_progress/agiletour-2021-tu-ne-le-sais-pas-encore-mais-tu-l-as-deja-documente/assets
  label: Assets slides agile tour 2021
  create: none
  match: "**/*"
- type: document
  path: side_projects_in_progress/agiletour-2021-tu-ne-le-sais-pas-encore-mais-tu-l-as-deja-documente/slides.md
  label: Slides Agile tour 2021
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
