package baldir.fr

import kotlinx.serialization.*
import kotlinx.serialization.json.Json
import java.io.File
import java.time.LocalDate
import java.time.LocalTime
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter

class App {
    val greeting: String
        /*

         * This Kotlin source file was generated by the Gradle 'init' task.
         */
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    val jsonfileName = args[0]
    val jsonData = File(jsonfileName).readText()
    val obj = toData(jsonData)
    File("${obj.display_id}.yml").writeText(toYmlText(obj))

}

fun toData(jsonData: String): Data {
    val json = Json(strictMode = false)

    // parsing data back
    val deserializer = Data.serializer()
    val obj = json.parse(deserializer, jsonData)
    return obj
}

fun toYmlText(data: Data): String {
    val speaker = """speaker:
    name: ${data.playlist_uploader}
#    twitter: SpeakerTwitterHandle (no @)"""

    val recordingDate = LocalDate.parse(data.upload_date, DateTimeFormatter.ofPattern("yyyyMMdd"))
    val recordingDateTimestamp = recordingDate.toEpochSecond(LocalTime.NOON, ZoneOffset.UTC)
    return """
# Editing guidelines: https://github.com/watch-devtube/contrib/#how-to-edit-video-metadata

${tags(data)}
$speaker
title: ${data.fulltitle}
# language: English
# category: conference # or vlog
recordingDate: $recordingDateTimestamp
description: "${data.description.replace("\n", "\\n")}"
            """.trimIndent()
}

private fun tags(date: Data): String {
    if (date.tags.isEmpty()) return ""

    val tagsList = date.tags.map { it -> "   - $it" }.joinToString(separator = "\n")
    val tags = """tags:
$tagsList"""
    return tags
}

@Serializable()
data class Data(
        val title: String,
        val fulltitle: String,
        val playlist_id: String? = null,
        val description: String,
        val playlist_uploader: String? = null,
        val uploader_id: String,
        val tags: List<String>,
        val upload_date: String,
        val display_id: String
)